### ISSUE TITLE
Failed to activate the autocomplete-solidity package

### ISSUE THREAD

**Issue by nwootton** [AustP/autocomplete-solidity#1]
1. Open Atom - previous pages/windows automatically open
2. Two of the files in the window are MetaCoin.sol & ConvertLib.sol example files from Ethereum tutorials
3. Crash report gets thrown

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [autocomplete-solidity](https://github.com/austp/autocomplete-solidity) package, v0.2.0
### Stack Trace

Failed to activate the autocomplete-solidity package

```
At Cannot read property 'functions' of undefined

TypeError: Cannot read property 'functions' of undefined
    at _parse (/Users/woottonn/.atom/packages/autocomplete-solidity/src/util/parser.js:225:46)
    at Object.parse (/Users/woottonn/.atom/packages/autocomplete-solidity/src/util/parser.js:534:33)
    at parse (/Users/woottonn/.atom/packages/autocomplete-solidity/src/autocomplete-solidity.js:36:28)
    at /Users/woottonn/.atom/packages/autocomplete-solidity/src/autocomplete-solidity.js:40:13
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:307:9)
    at Object.activate (/Users/woottonn/.atom/packages/autocomplete-solidity/src/autocomplete-solidity.js:31:24)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "atom-light-ui",
      "monokai-seti"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-solidity, v0.2.0
highlight-selected, v0.11.2
language-docker, v1.1.6
language-ethereum, v0.3.8
less-than-slash, v0.13.0
linter, v1.11.10
linter-csslint, v1.3.2
linter-docker, v0.1.2
linter-htmlhint, v1.2.0
linter-jshint, v2.1.0
linter-json-lint, v0.1.1
linter-sass-lint, v1.5.0
linter-solidity, v0.2.1
lisp-paredit, v0.5.3
minimap, v4.24.6
minimap-hide, v0.3.0
minimap-highlight-selected, v4.4.0
monokai-seti, v0.7.0
open-recent, v5.0.0
pigments, v0.29.2
pretty-json, v1.4.1
proto-repl, v1.1.11
react, v0.15.0
swackets, v0.10.0

# Dev
No dev packages
```

**Comment by AustP** [comment]
I just pushed v0.3.0 which added library support. Does this fix your issue?

**Comment by nwootton** [comment]
Updated and Atom now opens without throwing that error. Thanks.
