### ISSUE TITLE
Uncaught TypeError: Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by ghost** [AustP/autocomplete-solidity#10]
This error: `.atom/packages/autocomplete-solidity/src/providers/Provider.js:45`
happens when I open a new tab and start typing `contract`. More is not needed, then this appears:

```
TypeError: Cannot read property 'context' of undefined
    at BaseProvider.getStructure (/home/user/.atom/packages/autocomplete-solidity/src/providers/Provider.js:45:38)
    at BaseProvider.getSuggestions (/home/user/.atom/packages/autocomplete-solidity/src/providers/Provider.js:55:14)
    at providers.forEach.provider (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:300:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:271:21)
    at AutocompleteManager.findSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:263:23)
    at AutocompleteManager.requestNewSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1699:32)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:966:18)
    at TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1825:30)
    at mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:1372:25)
    at TextEditor.mergeSelections (/usr/share/atom/resources/app/src/text-editor.js:3208:26)
    at TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:3179:42)
    at TextEditor.mutateSelectedText (/usr/share/atom/resources/app/src/text-editor.js:1371:23)
    at TextEditor.insertText (/usr/share/atom/resources/app/src/text-editor.js:1337:23)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/usr/share/atom/resources/app/src/text-editor-component.js:1651:30)
```

**Comment by msemple1111** [comment]
same issue here, looks like its when the file hasn't been saved, works for me if you save the file first

**Comment by Monkpie** [comment]
Same goes for 'pragma.' Confirmed that saving beforehand resolves issue.
