### ISSUE TITLE
Failed to activate the autocomplete-solidity package

### ISSUE THREAD

**Issue by yjj828** [AustP/autocomplete-solidity#11]
**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [autocomplete-solidity](https://github.com/austp/autocomplete-solidity) package 0.3.4

Arguments to CompositeDisposable.add must have a .dispose() method
Show Stack Trace
The error was thrown from the autocomplete-solidity package. This issue has already been reported.
### Stack Trace

Failed to activate the autocomplete-solidity package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/composite-disposable.js:43:17)
    at Object.consumeProvider (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:89:27)
    at Object.consumeProvider_2 (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:62:23)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:397:75)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:233:20)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at packagesToEnable.forEach.name (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:440:30)
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:407:18)
    at Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:75:30)
    at PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

### Commands

```
     -4:16.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -3:04.7.0 core:move-right (input.hidden-input)
  3x -3:02.8.0 core:backspace (input.hidden-input)
     -2:59.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-solidity 0.3.4 
linter-solidity 0.5.0 
linter-solium 0.0.5 
```

**Comment by notOccupanther** [comment]
Having this issue also.  Was working fine, but stopped working last week.
Disabling and re-enabling the package throws this error.
