### ISSUE TITLE
Uncaught TypeError: Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by ghost** [AustP/autocomplete-solidity#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-solidity](https://github.com/austp/autocomplete-solidity) package 0.3.3

### Stack Trace

Uncaught TypeError: Cannot read property 'context' of undefined

```
At C:\Users\Nicolas Cantu\.atom\packages\autocomplete-solidity\src\providers\Provider.js:45

TypeError: Cannot read property 'context' of undefined
    at BaseProvider.getStructure (/packages/autocomplete-solidity/src/providers/Provider.js:45:38)
    at BaseProvider.getSuggestions (/packages/autocomplete-solidity/src/providers/Provider.js:55:14)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:1
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:1)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:1)
```

### Commands

```
  4x -3:03.0 core:confirm (input.hidden-input)
     -2:49.1.0 core:cut (input.hidden-input)
     -2:46.9.0 core:paste (input.hidden-input)
  2x -2:45.8.0 core:confirm (input.hidden-input)
     -2:05.2.0 core:save-as (input.hidden-input)
     -1:30.9.0 core:paste (div.)
     -1:27 core:save (input.hidden-input)
 21x -0:28.9.0 core:page-down (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-solidity 0.3.3 
language-ethereum 0.3.9 
pretty-json 1.6.3 
```

**Comment by ncantu** [comment]
yop
