### ISSUE TITLE
Uncaught TypeError: Cannot read property '' of undefined

### ISSUE THREAD

**Issue by ghost** [AustP/autocomplete-solidity#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-solidity](https://github.com/austp/autocomplete-solidity) package 0.3.3

### Stack Trace

Uncaught TypeError: Cannot read property '' of undefined

```
At C:\Users\Nicolas Cantu\.atom\packages\autocomplete-solidity\src\util\contracts.js:181

TypeError: Cannot read property '' of undefined
    at Contract.getVariableDefinitions (/packages/autocomplete-solidity/src/util/contracts.js:181:33)
    at TypeProvider.getDefinitions (/packages/autocomplete-solidity/src/providers/context-provider.js:108:38)
    at TypeProvider.getSuggestions (/packages/autocomplete-solidity/src/providers/Provider.js:59:35)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:1
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:1)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:1)
```

### Commands

```
     -1:30.5.0 core:copy (input.hidden-input)
     -1:17.8.0 core:save (input.hidden-input)
     -1:16.4.0 core:copy (input.hidden-input)
     -1:15.3.0 core:paste (input.hidden-input)
     -1:14.5.0 core:save (input.hidden-input)
     -1:12.7.0 core:copy (input.hidden-input)
     -1:06.7.0 core:paste (input.hidden-input)
  3x -1:05.0 core:save (input.hidden-input)
  2x -0:35.4.0 core:copy (input.hidden-input)
  2x -0:20.2.0 editor:newline (input.hidden-input)
     -0:19.3.0 snippets:next-tab-stop (input.hidden-input)
     -0:19.3.0 snippets:expand (input.hidden-input)
     -0:19.3.0 editor:indent (input.hidden-input)
     -0:18.9.0 core:paste (input.hidden-input)
  3x -0:16.2.0 core:backspace (input.hidden-input)
     -0:09.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-solidity 0.3.3 
language-ethereum 0.3.9 
pretty-json 1.6.3 
```

**Comment by AustP** [comment]
Could you include the solidity code that causes this error? And do the same for #5?

**Comment by gabrielmendanha** [comment]
@AustP I am getting the same error, using Atom but on MacOS High Sierra. Contract code anexed.
This happens at line 52.
[crowdsale.sol.zip](https://github.com/AustP/autocomplete-solidity/files/1423335/crowdsale.sol.zip)

**Comment by gabrielmendanha** [comment]
Line 52.
