### ISSUE TITLE
Uncaught TypeError: Cannot read property 'migrateIn' of undefined

### ISSUE THREAD

**Issue by MicahZoltu** [AustP/autocomplete-solidity#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [autocomplete-solidity](https://github.com/austp/autocomplete-solidity) package 0.3.3

### Stack Trace

Uncaught TypeError: Cannot read property 'migrateIn' of undefined

```
At C:\Users\micah\AppData\Local\atom\home\packages\autocomplete-solidity\src\util\contracts.js:181

TypeError: Cannot read property 'migrateIn' of undefined
    at Contract.getVariableDefinitions (/packages/autocomplete-solidity/src/util/contracts.js:181:33)
    at TypeProvider.getDefinitions (/packages/autocomplete-solidity/src/providers/context-provider.js:135:94)
    at TypeProvider.getSuggestions (/packages/autocomplete-solidity/src/providers/Provider.js:59:35)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
  2x -1:37.2.0 core:move-up (input.hidden-input)
     -1:36.7.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:36.4.0 editor:newline (input.hidden-input)
     -1:32.7.0 autocomplete-plus:cancel (input.hidden-input)
     -1:32.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -1:31.9.0 editor:select-to-first-character-of-line (input.hidden-input)
  2x -1:31.5.0 core:backspace (input.hidden-input)
  2x -1:28.7.0 core:move-down (input.hidden-input)
  2x -1:13.5.0 autocomplete-plus:confirm (input.hidden-input)
     -1:09.8.0 intentions:highlight (input.hidden-input)
     -1:09.7.0 core:save (input.hidden-input)
  2x -1:08.9.0 core:move-down (input.hidden-input)
  2x -1:01.5.0 editor:newline (input.hidden-input)
     -0:54 core:move-left (input.hidden-input)
     -0:40.4.0 editor:newline (input.hidden-input)
     -0:38 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-solidity 0.3.3 
busy-signal 1.4.3 
file-types 0.5.5 
intentions 1.1.2 
language-docker 1.1.8 
language-ethereum 0.3.9 
linter 2.2.0 
linter-docker 0.2.0 
linter-solidity 0.5.0 
linter-solium 0.0.3 
linter-ui-default 1.6.3 
python-debugger 0.2.0 
```

**Comment by AustP** [comment]
Could you post the code that this error occurs on?

**Comment by MicahZoltu** [comment]
Unfortunately it was a transient error as I was typing, so I'm not sure what exactly I had typed up at the time.  I can say with some amount of confidence that whatever I had typed was _not_ valid Solidity though.
